library(swirl)
swirl()
sapply(flags, unique)
vapply(flags, unique, numeric(1))
ok()
sapply(flags, class)
vapply(flags, class, character(1))
?tapply
table(flags$landmass)
table(flags$animate)
tapply(flags$animate, flags$landmass, mean)
tapply(flags$population, flags$red, summary )
tapply(flags$population, flags$red, summary)
tapply(flags$population, flags$landmass, summary)
exit
savehistory("~/SRT411/Swirl/Lab1/VapplyAndTapply.r")
swirl()
ls()
class(plants)
dim(plants)
nrow(plants)
ncol(plants)
object.size(plants)
names(plants)
head(plants)
head(plants, 10)
tail(plants, 15)
summary(plants)
table(plants$Active_Growth_Period)
str(plants)
savehistory("~/SRT411/Swirl/Lab1/LookingAtData.r")
